version: '3.1'

services:
  stats-server:
    build: ewm_stats/ewm_stats_server
    image: ewm_stats_server
    container_name: ewm_stats_server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ewm-stats

  stats-db:
    image: postgres:15.1-alpine
    container_name: ewm-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ewm-stats

  ewm-service:
    build: ewm_main
    image: ewm_main_service
    container_name: ewm_main_service
    ports:
      - "8080:8080"
